export TERM=xterm-256color

alias ls='ls --color'
alias ll='ls -l'

# git aliases
alias gs='git status'
alias gc='git commit'
alias gd='git diff'
alias gp='git push'
# /git

# prompt
parse_git_branch() {
	     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
     }
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "
# /prompt
