"
" Vundle plugin manager
set nocompatible              " required by vundle
filetype off                  " required by vundle


" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'itchyny/vim-gitbranch'       " to display git branch in status bar
Plugin 'itchyny/lightline.vim'       " light status bar
Plugin 'scrooloose/nerdtree'         " file navigator
Plugin 'Xuyuanp/nerdtree-git-plugin' " show git status in file tree
"Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'ap/vim-buftabline'
call vundle#end()
" /vundle


let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "m",
    \ "Staged"    : "s",
    \ "Untracked" : "u",
    \ "Renamed"   : "r",
    \ "Unmerged"  : "u",
    \ "Deleted"   : "x",
    \ "Dirty"     : "d",
    \ "Clean"     : "c",
    \ 'Ignored'   : 'i',
    \ "Unknown"   : "?"
    \ }


"
" configure lightline
" "
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ 'active': {
      \   'left': [ [ 'paste' ],
      \             [ 'gitbranch' ],
      \             [ 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'gitbranch#name'
      \ },
      \ }

if !has('gui_running')
  set t_Co=256
endif
" /lightline

"
" global behabiour
"
set hidden                     " allow navigation through unwritten buffers
syntax on
filetype plugin indent on
" /behavior

"
" shortcuts
"
map <silent> <F3> :NERDTreeToggle<CR>
nmap & :buffer1<CR>
nmap é :buffer2<CR>
nmap " :buffer3<CR>
nmap ' :buffer4<CR>
nmap c :!git commit %<CR>

command GC !git commit % -m "<args>"
" /shortcuts
