"
" Vundle plugin manager
set nocompatible              " required by vundle
filetype off                  " required by vundle


" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'itchyny/vim-gitbranch'       " to display git branch in status bar
Plugin 'itchyny/lightline.vim'       " light status bar
Plugin 'scrooloose/nerdtree'         " file navigator
Plugin 'Xuyuanp/nerdtree-git-plugin' " show git status in file tree
"Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'ap/vim-buftabline'
call vundle#end()
" /vundle


let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "m",
    \ "Staged"    : "s",
    \ "Untracked" : "u",
    \ "Renamed"   : "r",
    \ "Unmerged"  : "u",
    \ "Deleted"   : "x",
    \ "Dirty"     : "d",
    \ "Clean"     : "c",
    \ 'Ignored'   : 'i',
    \ "Unknown"   : "?"
    \ }


"
" configure lightline
" "
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'powerline',
      \ 'active': {
      \   'left': [ [ 'paste' ],
      \             [ 'gitbranch' ],
      \             [ 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'gitbranch#name'
      \ },
      \ }

if !has('gui_running')
  set t_Co=256
endif
" /lightline


"
" tabline
"
let g:buftabline_show=1     " only if >1 buffer
let g:buftabline_numbers=2  " ordinal number
" /tabline


"
" global behabiour
"
set hidden                     " allow navigation through unwritten buffers
syntax on
filetype plugin indent on
set autoindent

" https://stackoverflow.com/questions/2902048/vim-save-a-list-of-open-files-and-later-open-all-files
autocmd VimLeave * mksession! ~/.vim/shutdown_session.vim
command Rss :source ~/.vim/shutdown_session.vim
" autocmd VimEnter source ~/.vim/shutdown_session.vim<CR>
command Ss :mksession! ~/.vim/manual_session.vim
command Rs :source ~/.vim/manual_session.vim
" /behavior

"
" shortcuts
"
map <silent> <F3> :NERDTreeToggle<CR>
nmap & <Plug>BufTabLine.Go(1)
nmap é <Plug>BufTabLine.Go(2)
nmap " <Plug>BufTabLine.Go(3)
nmap ' <Plug>BufTabLine.Go(4)
nmap c :!git commit %<CR>

map <F10> :w<CR>:!'%:p'<CR>

command GC !git commit % -m "<args>"
" /shortcuts

"
" filetypes specific
"

autocmd FileType html setlocal tabstop=4

autocmd FileType javascript setlocal tabstop=4

" /filetypes
